# Copyright 2017-present, Bill & Melinda Gates Foundation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 00:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0002_auto_20161114_0746'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='observationcount',
            options={},
        ),
        migrations.AlterField(
            model_name='observationcount',
            name='codes',
            field=models.ManyToManyField(help_text=b'The codes used to classify the count.', to='studies.Variable'),
        ),
        migrations.AlterField(
            model_name='observationcount',
            name='study',
            field=models.ForeignKey(help_text=b'The study associated with the count.', on_delete=django.db.models.deletion.CASCADE, to='studies.Study'),
        ),
    ]
