# Copyright 2017-present, Bill & Melinda Gates Foundation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 12:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0003_auto_20161116_1639'),
    ]

    operations = [
        migrations.CreateModel(
            name='Count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(help_text='Number of observations associated with the specified study and codes.', null=True)),
                ('subjects', models.IntegerField(help_text='Number of subjects associated with the specified study and codes.', null=True)),
                ('codes', models.ManyToManyField(help_text='The codes used to classify the count.', to='studies.Variable')),
                ('study', models.ForeignKey(help_text='The study associated with the count.', on_delete=django.db.models.deletion.CASCADE, to='studies.Study')),
            ],
        ),
        migrations.RemoveField(
            model_name='observationcount',
            name='codes',
        ),
        migrations.RemoveField(
            model_name='observationcount',
            name='study',
        ),
        migrations.DeleteModel(
            name='ObservationCount',
        ),
    ]
