# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0004_auto_20161122_0413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='count',
            name='count',
            field=models.IntegerField(default=0, help_text='Number of observations associated with the specified study and codes.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='count',
            name='subjects',
            field=models.IntegerField(default=0, help_text='Number of subjects associated with the specified study and codes.'),
            preserve_default=False,
        ),
    ]
