# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 18:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0008_auto_20170123_0841'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(help_text='Column header name as it appears in study import file.', max_length=50, unique=True, verbose_name='Field Name')),
                ('label', models.CharField(blank=True, help_text='Field name as it should appear in this app (spaces allowed).', max_length=100, null=True, verbose_name='Label')),
                ('field_type', models.CharField(choices=[('list', 'List'), ('int', 'Integer'), ('str', 'Character String'), ('float', 'Decimal Number')], default='str', help_text='Type of values that will go in this field.', max_length=10, verbose_name='Field Type')),
                ('big_order', models.IntegerField(default=-1, help_text='Order in which this field will be diplayed on study list (negative value indicates field not shown).', verbose_name='Large Display Order')),
                ('lil_order', models.IntegerField(default=-1, help_text='Order in which this field will be diplayed on study filter (negative value indicates field not shown).', verbose_name='Small Display Order')),
            ],
            options={
                'verbose_name_plural': 'Study Fields',
            },
        ),
        migrations.CreateModel(
            name='StudyVariable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text='The value of this study variable', max_length=300, verbose_name='Value')),
            ],
            options={
                'verbose_name_plural': 'Study Variables',
            },
        ),
        migrations.AlterModelOptions(
            name='study',
            options={'verbose_name_plural': 'Studies'},
        ),
        migrations.RemoveField(
            model_name='study',
            name='analysis_folder',
        ),
        migrations.RemoveField(
            model_name='study',
            name='country',
        ),
        migrations.RemoveField(
            model_name='study',
            name='gest_age',
        ),
        migrations.RemoveField(
            model_name='study',
            name='grant_folder',
        ),
        migrations.RemoveField(
            model_name='study',
            name='intervention_type',
        ),
        migrations.RemoveField(
            model_name='study',
            name='short_description',
        ),
        migrations.RemoveField(
            model_name='study',
            name='short_id',
        ),
        migrations.RemoveField(
            model_name='study',
            name='start_year',
        ),
        migrations.RemoveField(
            model_name='study',
            name='status',
        ),
        migrations.RemoveField(
            model_name='study',
            name='stop_year',
        ),
        migrations.RemoveField(
            model_name='study',
            name='study_description',
        ),
        migrations.RemoveField(
            model_name='study',
            name='study_type',
        ),
        migrations.RemoveField(
            model_name='study',
            name='subject_count',
        ),
        migrations.AlterField(
            model_name='filter',
            name='study_field',
            field=models.ForeignKey(blank=True, help_text='The study field that this filter applies to.', null=True, on_delete=django.db.models.deletion.CASCADE, to='studies.StudyField', to_field='field_name', verbose_name='Study Field'),
        ),
        migrations.AddField(
            model_name='studyvariable',
            name='study',
            field=models.ForeignKey(help_text='The study id that this variable applies to.', on_delete=django.db.models.deletion.CASCADE, to='studies.Study', to_field='study_id'),
        ),
        migrations.AddField(
            model_name='studyvariable',
            name='study_field',
            field=models.ForeignKey(help_text='The study field that this variable applies to.', on_delete=django.db.models.deletion.CASCADE, to='studies.StudyField', to_field='field_name'),
        ),
        migrations.AlterUniqueTogether(
            name='studyvariable',
            unique_together=set([('study', 'study_field')]),
        ),
    ]
