# Copyright 2017-present, Bill & Melinda Gates Foundation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0009_auto_20170123_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='count',
            name='codes',
            field=models.ManyToManyField(db_index=True, help_text='The codes used to classify the count.', to='studies.Variable'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='code',
            field=models.CharField(db_index=True, help_text='Short identifying code to classify a condition.', max_length=10, unique=True, verbose_name='Code'),
        ),
        migrations.AlterIndexTogether(
            name='studyvariable',
            index_together=set([('study', 'study_field')]),
        ),
    ]
