# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 19:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0012_auto_20170129_2122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countcodescache',
            name='count',
        ),
        migrations.DeleteModel(
            name='CountCodesCache',
        ),
    ]
