# Copyright 2017-present, Bill & Melinda Gates Foundation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0013_auto_20170208_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyvariable',
            name='studies',
            field=models.ManyToManyField(blank=True, db_index=True, help_text='The studies that this variable applies to.', to='studies.Study'),
        ),
        migrations.AlterField(
            model_name='study',
            name='study_id',
            field=models.CharField(db_index=True, help_text='Unique ID to reference the study.', max_length=50, unique=True, verbose_name='Study ID'),
        ),
        migrations.AlterUniqueTogether(
            name='studyvariable',
            unique_together=set([('value', 'study_field')]),
        ),
        migrations.AlterIndexTogether(
            name='studyvariable',
            index_together=set([]),
        ),
        migrations.RemoveField(
            model_name='studyvariable',
            name='study',
        ),
    ]
