# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0013_auto_20170208_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyvariable',
            name='studies',
            field=models.ManyToManyField(blank=True, db_index=True, help_text='The studies that this variable applies to.', to='studies.Study'),
        ),
        migrations.AlterField(
            model_name='study',
            name='study_id',
            field=models.CharField(db_index=True, help_text='Unique ID to reference the study.', max_length=50, unique=True, verbose_name='Study ID'),
        ),
        migrations.AlterUniqueTogether(
            name='studyvariable',
            unique_together=set([('value', 'study_field')]),
        ),
        migrations.AlterIndexTogether(
            name='studyvariable',
            index_together=set([]),
        ),
        migrations.RemoveField(
            model_name='studyvariable',
            name='study',
        ),
    ]
