# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2020-04-20 04:35
from __future__ import unicode_literals

from django.db import migrations, transaction
import os

studyfield_sql_path = os.path.join(os.path.dirname(__file__), '../../data/sql/002_update_studies_studyfield.sql')
studyfield_sql = 'SELECT 0;'

if os.path.exists(studyfield_sql_path):
    with open(studyfield_sql_path, 'r') as f:
        studyfield_sql = f.read()


def fix_study_variable_list(apps, schema_editor):
    StudyVariable = apps.get_model('studies', 'StudyVariable')
    objs_to_split = StudyVariable.objects.filter(study_field__field_type='list', value__contains=',')

    sep = ','
    with transaction.atomic():
        for obj in objs_to_split:
            # SV.split_list(obj)  # because Django is special, copy the code from StudyVariable.split_list
            if sep not in obj.value:
                return
            for val in obj.value.split(sep):
                v = val.replace(' ', '')
                study_var, _ = StudyVariable.objects.get_or_create(study_field=obj.study_field, value=str(v))
                study_var.studies.add(*[s for s in obj.studies.all()])
            obj.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0014_auto_20170214_0852'),
    ]

    operations = [
        migrations.RunSQL(studyfield_sql),
        migrations.RunPython(fix_study_variable_list)
    ]
