# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-14 15:46
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='country',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=13), help_text='List of countries involved in the study.', null=True, size=None, verbose_name='Country'),
        ),
    ]
