# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 00:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0002_auto_20161114_0746'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='observationcount',
            options={},
        ),
        migrations.AlterField(
            model_name='observationcount',
            name='codes',
            field=models.ManyToManyField(help_text=b'The codes used to classify the count.', to='studies.Variable'),
        ),
        migrations.AlterField(
            model_name='observationcount',
            name='study',
            field=models.ForeignKey(help_text=b'The study associated with the count.', on_delete=django.db.models.deletion.CASCADE, to='studies.Study'),
        ),
    ]
