# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-20 13:16
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0006_auto_20161123_0527'),
    ]

    operations = [
        migrations.AddField(
            model_name='filter',
            name='widget',
            field=models.CharField(choices=[('checkbox', 'Checkboxes'), ('double slider', 'Double Slider'), ('discrete slider', 'Discrete Slider')], default='checkbox', help_text='\n        The widget used to display the filter', max_length=20),
        ),
        migrations.AddField(
            model_name='filter',
            name='widget_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, help_text='\n        Specifies options to customize the widget as JSON.', verbose_name='Widget JSON'),
        ),
        migrations.AlterField(
            model_name='study',
            name='study_type',
            field=models.CharField(help_text='The type of study carried out.', max_length=50, null=True, verbose_name='Study Type'),
        ),
    ]
