# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0009_auto_20170123_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='count',
            name='codes',
            field=models.ManyToManyField(db_index=True, help_text='The codes used to classify the count.', to='studies.Variable'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='code',
            field=models.CharField(db_index=True, help_text='Short identifying code to classify a condition.', max_length=10, unique=True, verbose_name='Code'),
        ),
        migrations.AlterIndexTogether(
            name='studyvariable',
            index_together=set([('study', 'study_field')]),
        ),
    ]
