# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2020-04-20 04:35
from __future__ import unicode_literals

from django.db import migrations, transaction
import os
from studies.models import StudyVariable

studyfield_sql_path = os.path.join(os.path.dirname(__file__), '../../data/sql/002_update_studies_studyfield.sql')
studyfield_sql = 'SELECT 0;'

if os.path.exists(studyfield_sql_path):
    with open(studyfield_sql_path, 'r') as f:
        studyfield_sql = f.read()


def fix_study_variable_list(apps, schema_editor):
    objs_to_split = StudyVariable.objects.filter(study_field__field_type='list', value__contains=',')

    with transaction.atomic():
        for obj in objs_to_split:
            print('-' * 80)
            print('Splitting StudyVariable: {0}'.format(obj.value))
            obj.split_list()
            print('After Splitting StudyVariable:')
            for split_var in obj.split_variables:
                print('  {0}'.format(split_var.value))


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('studies', '0014_auto_20170214_0852'),
    ]

    operations = [
        migrations.RunSQL("SET session_replication_role = 'replica';"),
        migrations.RunSQL('UPDATE studies_domain SET code = upper(code);'),
        migrations.RunSQL('UPDATE studies_studyfield SET field_name = upper(field_name);'),
        migrations.RunSQL('UPDATE studies_studyvariable SET study_field_id = upper(study_field_id);'),
        migrations.RunSQL('UPDATE studies_filter SET study_field_id = upper(study_field_id) WHERE study_field_id IS NOT NULL;'),
        migrations.RunSQL("SET session_replication_role = 'origin';"),
        migrations.RunSQL(studyfield_sql),
        migrations.RunSQL('ALTER TABLE studies_domain ADD CONSTRAINT studies_domain_check_upper_code CHECK (code = upper(code));'),
        migrations.RunSQL('ALTER TABLE studies_studyfield ADD CONSTRAINT studies_studyfield_check_upper_field_name CHECK (field_name = upper(field_name));'),
        migrations.RunSQL('ALTER TABLE studies_studyvariable ADD CONSTRAINT studies_studyvariable_check_upper_study_field_id CHECK (study_field_id = upper(study_field_id));'),
        migrations.RunSQL('ALTER TABLE studies_filter ADD CONSTRAINT studies_filter_check_upper_study_field_id CHECK (study_field_id = upper(study_field_id));'),
        migrations.RunPython(fix_study_variable_list)
    ]
